apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ojxyye6dq-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:17e8b966ecc359525f3b535e7d1192baa8da772b@sha256:8cb8d17d0607cd7c6abf072cf6f679e07ca59aed0ddaf4d74ffe8151b63d4ce9
          name: container-image
